
spring.application.name=react-crash-course
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=notes
spring.mongodb.authentication-database=admin
spring.mongodb.username=admin
spring.mongodb.password=admin
spring.mongodb.representation.uuid=standard
spring.mvc.servlet.path=/api
